version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk17
    ports: 
      - "8080:8080"
    privileged: true
    user: root
    volumes: 
      - ./jenkins_home:/var/jenkins_home
    networks:
      - net 
networks:
  net: